FROM alpine:3.11 as Builder
WORKDIR /app
COPY superflare ./
RUN ls -al
RUN apk add upx && \
    upx -9 -o superflare.minify superflare && \
    mv superflare.minify superflare
RUN ls -al

FROM arm32v6/alpine:3.16
COPY --from=Builder /app/superflare /bin/superflare
ENV TZ=Asia/Shanghai
RUN apk add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    rm -rf /var/cache/apk/*
EXPOSE 5005
WORKDIR /app
CMD ["superflare"]