Title: SuperFlare
Footer: "<a href=\"https://github.com/junfuchang/superflare\" target=\"_blank\" rel=\"noopener noreferrer\">\U0001F973可自定义页脚</a>"
SiteIconMode: mdi
OpenAppNewTab: true
OpenBookmarkNewTab: true
ShowTitle: true
Greetings: ""
ShowSearchComponent: true
DisabledSearchAutoFocus: false
SearchMode: bookmarks
SearchEngine: bing
SearchEngineOpenMode: new-tab
ShowDateTime: true
ShowApps: true
ShowFavorites: true
ShowBookmarks: true
HideSettingButton: false
HideHelpButton: true
HideWarningsButton: false
Theme: onedark
ThemeBase: onedark
EnableEncryptedLink: false
IconMode: FILLING
KeepLetterCase: false
Locale: zh
LoginUser: admin
LoginPass: admin
BackgroundImageMode: url
BackgroundOpacity: 100
GlassEffect: none
GlassIntensity: 30
HomeMaxColumns: 5
HomeMaxWidth: 1600
