ARG FLARE_BASE_IMAGE
FROM $FLARE_BASE_IMAGE AS Builder
RUN go run build/build.go
RUN export VERSION=$(cat RELEASE_VERSION) && \
    export COMMIT=$(cat RELEASE_COMMIT) && \
    export BUILD_DATE=`date +%FT%T%z` && \
    echo "$BUILD_DATE / $COMMIT / $VERSION" && \
    GOARCH=amd64 go build -ldflags "-w -s -X 'github.com/soulteary/version-kit.Version=$VERSION' -X 'github.com/soulteary/version-kit.Commit=$COMMIT' -X 'github.com/soulteary/version-kit.BuildDate=$BUILD_DATE'" -o superflare main.go
RUN upx -9 -o superflare.minify superflare && mv superflare.minify superflare


FROM alpine:3.16
COPY --from=Builder /app/superflare /bin/superflare
ENV TZ=Asia/Shanghai
RUN apk add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    rm -rf /var/cache/apk/*
WORKDIR /app
CMD ["superflare"]