# Traefik 快速上手和使用，可参考 https://github.com/soulteary/traefik-example/
version: '3.6'

services:
  superflare:
    image: junfuchang/superflare
    restart: always
    # 默认无需添加任何参数，如有特殊需求
    # 历史 Docker 示例，当前文档请参考仓库根目录 README 与 docs/legacy-docker
    command: superflare
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.traefik-superflare-http.middlewares=https-redirect@file"
      - "traefik.http.routers.traefik-superflare-http.entrypoints=http"
      - "traefik.http.routers.traefik-superflare-http.rule=Host(`superflare.example.com`)"
      - "traefik.http.routers.traefik-superflare-http.service=dashboard@internal"

      - "traefik.http.routers.traefik-superflare-https.entrypoints=https"
      - "traefik.http.routers.traefik-superflare-https.rule=Host(`superflare.example.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.traefik-superflare-https.tls=true"

      - "traefik.http.services.traefik-superflare-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.traefik-superflare-backend.loadbalancer.server.port=5005"
    networks:
      - traefik
    expose:
      - 5005
    volumes:
      - ./app:/app

networks:
  traefik:
    external: true
